code: "<YOUR_DISCORD_INVITE_CODE>" # Replace with your actual Discord invite code
join: "<YOUR_JOIN_URL>" # Replace with your discord join URL (exemple : https://discord.gg/your-invite-code)
article: true # Set to true if you want to display the article section